apiVersion: v1
kind: Pod
metadata:
  name: non-root-user-pod
  namespace: audit-zone
spec:
  containers:
    - name: non-root-user-pod
      image: nginx
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true