apiVersion: v1
kind: Pod
metadata:
  name: non-privileged-pod
  namespace: audit-zone
spec:
  containers:
  - name: non-privileged-pod
    image: nginx
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 999
      runAsGroup: 999
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
