apiVersion: v1
kind: Pod
metadata:
  name: non-hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: non-hostpath-pod
      image: nginx
      securityContext:
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: host
          mountPath: /host
  volumes:
    - name: host
      emptyDir: {}