apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
  namespace: audit-zone
spec:
  containers:
    - name: root-user-pod
      image: nginx
      securityContext:
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL